# Users schema

# --- !Ups

CREATE TABLE MESSAGE_ENTITY (
    id bigint NOT NULL,
    user varchar(50),
    message varchar(255),
    CONSTRAINT PK_MESSAGE_ENTITY PRIMARY KEY (id)
);

CREATE SEQUENCE MESSAGE_ENTITY_SEQ START WITH 1000;

# --- !Downs

DROP TABLE IF EXISTS MESSAGE_ENTITY;

DROP SEQUENCE IF EXISTS MESSAGE_ENTITY_SEQ;